<?php

namespace ContainerXd6X1In;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XzHH6bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Xz_hH6b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xz_hH6b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.Xz_hH6b.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.Xz_hH6b": it needs an instance of "App\\Entity\\Comment" but this type has been excluded in "config/services.yaml".'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'commentRepository' => 'App\\Repository\\CommentRepository',
        ]);
    }
}
