<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDnVwEDj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDnVwEDj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDnVwEDj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDnVwEDj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDnVwEDj\App_KernelDevDebugContainer([
    'container.build_hash' => 'DnVwEDj',
    'container.build_id' => '139ee7dc',
    'container.build_time' => 1682103979,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDnVwEDj');
