<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container25xtjLx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container25xtjLx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container25xtjLx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container25xtjLx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container25xtjLx\App_KernelDevDebugContainer([
    'container.build_hash' => '25xtjLx',
    'container.build_id' => '5b20a024',
    'container.build_time' => 1682114234,
], __DIR__.\DIRECTORY_SEPARATOR.'Container25xtjLx');
