<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLIelWYe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLIelWYe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLIelWYe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLIelWYe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLIelWYe\App_KernelDevDebugContainer([
    'container.build_hash' => 'LIelWYe',
    'container.build_id' => '1ce35bff',
    'container.build_time' => 1682200072,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLIelWYe');
